//
//  GameViewController.swift
//  SwiftGame
//
//  Created by Uzair on 02/05/2019.
//  Copyright © 2019 Uzair. All rights reserved.
//

import UIKit
import SpriteKit
import GameplayKit

class GameViewController: UIViewController { //this class is autogenerated when creating a SpriteKit game with Swift 5 and Xcode 10.2
    public static var score = 0
    var gameScene : GameScene!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        // Load 'GameScene.sks' as a GKScene. This provides gameplay related content
        // including entities and graphs.
        if let scene = GKScene(fileNamed: "GameScene") {
            
            // Get the SKScene from the loaded GKScene
            if let sceneNode = scene.rootNode as! GameScene? {
                
                // Copy gameplay related content over to the scene
                
                // Set the scale mode to scale to fit the window
                sceneNode.scaleMode = .aspectFill
                sceneNode.gameController = self //this variable is in gameScene and gets set here for methods which require a view controller.
                gameScene = sceneNode //gives this view a local gameScene variable.
                
                // Present the scene
                if let view = self.view as! SKView? {
                    view.presentScene(sceneNode)
                    
                    view.ignoresSiblingOrder = true
                    
                    view.showsFPS = true
                    view.showsNodeCount = true
                }
            }
        }
    }
    
    override var shouldAutorotate: Bool {
        return true
    }

    override var supportedInterfaceOrientations: UIInterfaceOrientationMask {
        if UIDevice.current.userInterfaceIdiom == .phone {
            return .landscapeLeft
        } else {
            return .landscapeRight
        }
    }

    override var prefersStatusBarHidden: Bool {
        return true
    }
    
    func gameOver() {
        gameScene.removeAllChildren() //removes all the children as in the scene nodes
        gameScene.removeAllActions() //removes all actions such as sequences and timers
        let vc = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "highScore") as! HighScoreViewController //high score view controller
        self.present(vc, animated: true, completion: nil) //go to high scores
    }
    
    public func makeToast(controller: UIViewController, message: String, dur: Double) { //my own toast function
        let toast = UIAlertController(title: nil, message: message, preferredStyle: .alert)
        toast.view.alpha = 0.6
        toast.view.layer.cornerRadius = 15
        controller.present(toast, animated: true)
        DispatchQueue.main.asyncAfter(deadline: DispatchTime.now() + dur) { //show text for dur
            toast.dismiss(animated: true)
        }
    }
    
    override func motionBegan(_ motion: UIEvent.EventSubtype, with event: UIEvent?) {
        if motion == .motionShake {
            gameScene.shake() //if the phone is shook this is activated
        }
    }
}
